// angular-frontend/result/src/app/components/pokemon-detail/pokemon-detail.component.ts
import { Component, Input } from '@angular/core';
import { Pokemon } from 'src/app/data/model';

@Component({
  selector: 'app-pokemon-detail',
  templateUrl: './pokemon-detail.component.html',
  styleUrls: ['./pokemon-detail.component.scss'],
})
export class PokemonDetailComponent {
  @Input() selectedPokemon: Pokemon | undefined;
}

<div *ngIf="selectedPokemon">
  <h4>{{ selectedPokemon.name }}</h4>

  <img
    [alt]="selectedPokemon.name"
    [src]="selectedPokemon.sprites.front_default"
  />

  <button>Throw Poké Ball</button>
</div>

// vue-frontend/-assignment/src/components/pokemon-detail/PokemonDetail.vue
<template>
  <div class="c-pokemon-detail">
    <h4>{{ prop.pokemon.name }}</h4>
    <img
      class="visual"
      :alt="prop.pokemon.name"
      :src="prop.pokemon.sprites.front_default"
    />

    <button :disabled="isCaught">
      Throw Poke Ball
    </button>
  </div>
</template>

<style lang="scss">
@import './PokemonDetail.scss';
</style>

<script setup lang="ts">
import { defineProps, defineEmits } from 'vue';
import { Pokemon } from '@/data/model';

const prop = defineProps<{ pokemon: Pokemon; isCaught: boolean }>();
</script>
