// react-frontend/result/src/components/PokemonDetail.tsx
import { Pokemon } from "../data/model";

type PokemonDetailProps = {
  pokemon: Pokemon;
  isCaught: boolean;
  onThrowPokeBall: (pokemonId: number) => boolean;
};

const PokemonDetail = (props: PokemonDetailProps) => {
  const { pokemon, onThrowPokeBall, isCaught } = props;

  return (
    <div className="c-pokemon-detail">
      <h4>{pokemon.name}</h4>
      <img
        className="visual"
        alt={pokemon.name}
        src={pokemon.sprites.front_default}
      />

      <button disabled={isCaught} onClick={() => onThrowPokeBall(pokemon.id)}>
        Throw Poke Ball
      </button>
    </div>
  );
};

export default PokemonDetail;

// vue-frontend/result/src/components/pokemon-detail/PokemonDetail.vue
<template>
  <div class="c-pokemon-detail">
    <h4>{{ prop.pokemon.name }}</h4>
    <img
      class="visual"
      :alt="prop.pokemon.name"
      :src="prop.pokemon.sprites.front_default"
    />

    <button :disabled="isCaught" @click="throwPokeBall">
      Throw Poke Ball
    </button>
  </div>
</template>

<style lang="scss">
@import './PokemonDetail.scss';
</style>

<script setup lang="ts">
import { defineProps, defineEmits } from 'vue';
import { Pokemon } from '@/data/model';

const emit = defineEmits(['throw-poke-ball']);
const prop = defineProps<{ pokemon: Pokemon; isCaught: boolean }>();

function throwPokeBall() {
  emit('throw-poke-ball', prop.pokemon?.id);
}
</script>
