// react-frontend/result/src/components/PokemonList.tsx
import { Pokemon } from "../data/model";
import PokemonSummary from "./PokemonSummary";

type PokemonListProps = {
  pokemon: Pokemon[];
  isCaught: (id: number) => boolean;
  onSelect: (pokemonId: number) => void;
};

const PokemonList = (props: PokemonListProps) => {
  const { pokemon, isCaught, onSelect } = props;

  return (
    <div className="list">
      {pokemon.map((pokemon) => (
        <PokemonSummary
          key={pokemon.id}
          onSelect={onSelect}
          pokemon={pokemon}
          isCaught={isCaught(pokemon.id)}
        />
      ))}
    </div>
  );
};

export default PokemonList;

// vue-frontend/src/components/PokemonList.vue
<template>
  <template v-if="pokemon">
    <PokemonSummary
      @select="$emit('select', $event)"
      v-for="(pokemon, index) in props.pokemon"
      :pokemon="pokemon"
      :key="index"
      :isCaught="isCaught(pokemon.id)"
    />
  </template>
</template>

<script setup lang="ts">
import { defineProps, defineEmits } from 'vue';
import { Pokemon, Item } from '@/data/model';
import PokemonSummary from '@/components/PokemonSummary.vue';

const props = defineProps<{
  pokemon: Pokemon[];
  items: Item[];
  caughtIds: number[];
}>();
defineEmits(['select']);

function isCaught(id: number) {
  return props.caughtIds.some((x) => x === id);
}
</script>
